trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  displayName: 'MSVC Umgebung einrichten'
  inputs:
    script: |
      for /f "tokens=*" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do (
        call "%%i\VC\Auxiliary\Build\vcvarsall.bat" x86
      )

- script: |
    call s/e.bat
  displayName: 's/e.bat Ausführen'
  workingDirectory: '$(System.DefaultWorkingDirectory)'