trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  displayName: 'Build sss.exe'
  inputs:
    script: |
      @echo off
      for /f "tokens=*" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do (
        call "%%i\VC\Auxiliary\Build\vcvarsall.bat" x86
        pushd $(Build.BinariesDirectory)
        cl.exe /Od /utf-8 /D_CRT_SECURE_NO_WARNINGS /std:clatest -MTd -nologo -fp:fast -fp:except- -Gm- -GR- -EHa- -Zo -Oi -WX -W4 -wd4624 -wd4530 -wd4244 -wd4201 -wd4100 -wd4101 -wd4189 -wd4505 -wd4127 -wd4702 -wd4310 -wd4018 -FC -Z7 -I$(System.DefaultWorkingDirectory)\q -I$(System.DefaultWorkingDirectory)\t $(System.DefaultWorkingDirectory)\b\sss.c /Fesss.exe /link -incremental:no -opt:ref
        popd
      )
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.BinariesDirectory)\sss.exe'
    artifactName: 'sss'
